== Voting
Funnily enough, one of the areas where blockchain technology could make the biggest impact has little to do with business, and much to do with politics: voting. Some think the ledger’s decentralised, tamper-proof nature make it safe enough to allow fraud-free online elections: voters would just get vote tokens and transfer them in order to signal their preference. The idea has already been proposed by Ethereum-powered nonprofit organisation https://www.democracy.earth/[Sovereign], and actually piloted and green-lighted in Estonia – although in the apolitical context of e-voting in corporate shareholder meetings. Even the European parliament devoted a short white paper to assessing blockchain-based electronic voting.

More recently, during a talk in Barcelona, bitcoin developer and anarchist firebrand https://twitter.com/amirpolyteknik?lang=en[Amir Taaki] proposed using blockchain technology for rerunning the Catalan independence referendum online, a method which, he argued, would neutralise the repression of Spain’s central government.

Adding blockchain to the election process could change the way we think about voting, says http://www.zyen.com/index.php?option=com_content&view=article&id=67&Itemid=9[Michael Mainelli], director of financial thinktank Z/Yen. For instance, he says, blockchain could allow for “continuous voting” – the casting of voting every week or month – and “transferable voting”. “The idea is that I have a vote but I don’t know enough about a topic, so I give my vote to someone who knows a lot about that, and let them make the choice,” Mainelli says. “Of course, this would also work in corporate governance.”
